// frontend/src/views/Home.jsx
import React, { useRef, useState, useEffect, useMemo } from 'react'
import { useNavigate } from 'react-router-dom'
import gsap from 'gsap'
import { ScrollTrigger } from 'gsap/ScrollTrigger'
import LuxuryButton from '@/components/LuxuryButton'
import Lock3D from '@/components/Lock3D'
import MarqueeStrip from '@/components/MarqueeStrip'
import SEO from '@/components/SEO'
import { useContentStore } from '@/stores/contentStore'
import { usePageLoaderStore } from '@/hooks/usePageLoader'
import {
  ShieldCheckIcon,
  EyeIcon,
  BoltIcon,
  ChartBarIcon,
  ExclamationTriangleIcon,
  ClockIcon,
} from '@heroicons/react/24/outline'

gsap.registerPlugin(ScrollTrigger)

const storyAchievements = [
  {
    id: 'threats',
    display: '50M+',
    label: 'Threats Blocked Daily',
    desc: 'AI-powered detection blocks millions of attacks across every vector, every day.',
    icon: ShieldCheckIcon,
  },
  {
    id: 'uptime',
    display: '99.9%',
    label: 'Uptime Guarantee',
    desc: 'Enterprise-grade availability so your security coverage never has a gap.',
    icon: ClockIcon,
  },
  {
    id: 'clients',
    display: '500+',
    label: 'Enterprise Clients',
    desc: 'Trusted by organisations across finance, healthcare, government and tech.',
    icon: ChartBarIcon,
  },
  {
    id: 'monitoring',
    display: '24/7',
    label: 'Security Monitoring',
    desc: 'Our SOC team monitors your infrastructure around the clock—zero blind spots.',
    icon: EyeIcon,
  },
]

const featureIcons = [
  ShieldCheckIcon,
  EyeIcon,
  BoltIcon,
  ChartBarIcon,
  ExclamationTriangleIcon,
  ClockIcon,
]

function getFeatureIcon(i) {
  const Icon = featureIcons[i % featureIcons.length]
  return <Icon className="feat-icon-svg" />
}

function Home() {
  const navigate = useNavigate()
  const store = useContentStore()
  const pageLoaded = usePageLoaderStore(state => state.pageLoaded)

  const [featActiveIdx, setFeatActiveIdx] = useState(0)

  // Refs
  const lockFloatRef = useRef(null)
  const lockRef = useRef(null)
  const heroRef = useRef(null)
  const marqueeWrapRef = useRef(null)
  const achieveStoryRef = useRef(null)
  const featuresSectionRef = useRef(null)
  const featHeadlineRef = useRef(null)
  const featContentRef = useRef(null)
  const headlineRef = useRef(null)
  const panelRefs = useRef([])

  const setLockRot = (y, z = 0) => {
    if (lockRef.current) {
      lockRef.current.setScrollRotation(y, z)
    }
  }

  // Computed values derived from contentStore
  const heroTitle = useMemo(() => {
    const t = store.hero?.title || 'Secure Your Digital Assets with'
    return t.replace(/\s*(HavoSec|with HavoSec)\s*$/i, '').trim() + ' '
  }, [store.hero?.title])

  const animationSettings = useMemo(() => ({
    modelPath: store.hero?.animation?.modelPath || '/lock.glb',
    primaryColor: store.hero?.animation?.primaryColor || '#673ee6',
    secondaryColor: store.hero?.animation?.secondaryColor || '#00b090',
    scale: store.hero?.animation?.scale || 3,
    autoRotate: true,
    rotationSpeed: store.hero?.animation?.rotationSpeed || 0.005,
  }), [store.hero?.animation])

  const displayFeatures = useMemo(() => {
    return store.features?.items?.length ? store.features.items : [
      {
        title: 'Real-Time Threat Detection',
        description: 'AI-powered detection identifies attacks in milliseconds.',
        benefit: 'Stay ahead of emerging threats',
      },
      {
        title: 'Advanced Monitoring',
        description: 'Comprehensive visibility across your entire digital infrastructure.',
        benefit: 'Complete oversight of your security landscape',
      },
      {
        title: 'Automated Response',
        description: 'Instant automated responses to security threats.',
        benefit: 'Minimize damage immediately',
      },
      {
        title: 'Analytics Dashboard',
        description: 'Rich analytics and reporting for security insights.',
        benefit: 'Data-driven security decisions',
      },
    ]
  }, [store.features?.items])

  const demoTitle = useMemo(() => store.hero?.demoTitle || 'Ready to Protect Your', [store.hero?.demoTitle])
  const demoTitle2 = useMemo(() => store.hero?.demoTitle2 || 'Organization?', [store.hero?.demoTitle2])
  const demoDescription = useMemo(() => store.hero?.demoDescription || 'Get a personalized demonstration of HavoSec.', [store.hero?.demoDescription])
  const demoButtonText = useMemo(() => store.hero?.demoButtonText || 'Schedule Your Demo Today', [store.hero?.demoButtonText])
  const demoButtonLink = useMemo(() => store.hero?.demoButtonLink || '/book-demo', [store.hero?.demoButtonLink])

  const scrollDown = () => {
    window.scrollBy({ top: window.innerHeight, behavior: 'smooth' })
  }

  // Hero Entry Animation
  useEffect(() => {
    if (!pageLoaded) return

    gsap.set(['.hero-left', '.hero-right'], { opacity: 0 })
    const tl = gsap.timeline({ defaults: { ease: 'power3.out' } })
    tl.fromTo(
      '.hero-left',
      { x: -80, opacity: 0 },
      { x: 0, opacity: 1, duration: 1.2 }
    )
      .fromTo(
        '.hero-right',
        { x: 80, opacity: 0 },
        { x: 0, opacity: 1, duration: 1.2 },
        '-=1.0'
      )
  }, [pageLoaded])

  // Scroll Animations
  useEffect(() => {
    const lockFloat = lockFloatRef.current
    const marqueeWrap = marqueeWrapRef.current
    const hero = heroRef.current
    const achieveStory = achieveStoryRef.current
    const featuresSection = featuresSectionRef.current
    const featHeadline = featHeadlineRef.current
    const featContent = featContentRef.current

    if (!lockFloat || !marqueeWrap || !hero || !achieveStory || !featuresSection) return

    // Clear transforms left by a hot reload or an earlier animation version.
    // Only the complete heading groups are allowed to own a heading transform.
    const achieveHeading = headlineRef.current?.querySelector('.achieve-heading')
    const featureHeading = featHeadline?.querySelector('.feature-heading')
    const titleLines = [
      headlineRef.current?.querySelector('.achieve-headline'),
      featHeadline?.querySelector('.feat-headline'),
    ].filter(Boolean)
    gsap.set(titleLines, { clearProps: 'transform,opacity' })
    gsap.set([achieveHeading, featureHeading].filter(Boolean), { x: '110vw', autoAlpha: 0 })

    // Lock stays centered and does not participate in scroll-driven motion.
    gsap.set(lockFloat, { xPercent: -50, yPercent: -50 })

    // Phase 1->2: keep steady center
    const stMarquee = ScrollTrigger.create({
      trigger: marqueeWrap,
      start: 'top 80%',
      end: 'bottom 20%',
      scrub: true,
      onUpdate() {
        gsap.set(lockFloat, { yPercent: -50 })
      },
    })

    // HERO -> ACHIEVEMENTS
    const HEADING_PHASE = 0.2

    // ACHIEVEMENTS CYCLE
    const stAchieve = ScrollTrigger.create({
      trigger: achieveStory,
      start: 'top top',
      end: 'bottom bottom',
      scrub: 1.2,
      onUpdate(self) {
        const p = self.progress
        const heading = headlineRef.current?.querySelector('.achieve-heading')

        if (p < HEADING_PHASE) {
          const hp = p / HEADING_PHASE
          const xVW = 100 - hp * 310
          if (heading) {
            gsap.set(heading, { x: `${xVW}vw`, autoAlpha: 1 })
          }
          // Hide all panels
          panelRefs.current.forEach(el => {
            if (el) gsap.set(el, { opacity: 0, y: 40 })
          })
        } else {
          if (heading) gsap.set(heading, { x: '-120vw', autoAlpha: 0 })

          const pp = (p - HEADING_PHASE) / (1 - HEADING_PHASE)
          const num = storyAchievements.length

          panelRefs.current.forEach((el, i) => {
            if (!el) return
            const s0 = i / num
            const s1 = (i + 1) / num
            let op = 0
            let y = 40
            if (pp >= s0 && pp < s1) {
              const loc = (pp - s0) / (s1 - s0)
              if (loc < 0.2) {
                op = loc / 0.2
                y = 40 * (1 - op)
              } else if (loc > 0.8) {
                op = (1 - loc) / 0.2
                y = 0
              } else {
                op = 1
                y = 0
              }
            }
            const direction = i % 2 === 0 ? -1 : 1
            gsap.set(el, {
              opacity: op,
              x: direction * 48 * (1 - op),
              y,
              rotationY: direction * 18 * (1 - op),
              scale: 0.93 + op * 0.07,
            })
          })

        }
      },
    })

    // FEATURES DETAIL CYCLE
    let lastActiveIdx = -1
    const stFeaturesCycle = ScrollTrigger.create({
      trigger: featuresSection,
      start: 'top top',
      end: 'bottom bottom',
      scrub: 1.2,
      onUpdate(self) {
        const p = self.progress
        const totalFeatures = displayFeatures.length
        const headingPhase = 1 / (totalFeatures + 1)
        const heading = featHeadline?.querySelector('.feature-heading')

        if (p < headingPhase) {
          const hp = p / headingPhase
          const xVW = 100 - hp * 310
          if (heading) gsap.set(heading, { x: `${xVW}vw`, autoAlpha: 1 })
          if (featContent) gsap.set(featContent, { opacity: 0, y: 150 })
        } else {
          if (heading) gsap.set(heading, { x: '-120vw', autoAlpha: 0 })

          const pp = (p - headingPhase) / (1 - headingPhase)
          const entryFraction = 0.08

          if (pp < entryFraction) {
            const entryP = pp / entryFraction
            if (featContent) {
              gsap.set(featContent, {
                opacity: Math.pow(entryP, 1.5),
                y: 150 * (1 - entryP),
              })
            }
          } else {
            if (featContent) gsap.set(featContent, { opacity: 1, y: 0 })
          }

          const idx = Math.min(Math.floor(pp * totalFeatures), totalFeatures - 1)
          if (idx !== lastActiveIdx) {
            lastActiveIdx = idx
            setFeatActiveIdx(idx)
          }
        }
      },
    })

    return () => {
      stMarquee.kill()
      stAchieve.kill()
      stFeaturesCycle.kill()
    }
  }, [displayFeatures.length])

  return (
    <div className="home-page">
      <SEO
        title="A Autonomous Cybersecurity Platform"
        description="Protect your organization with HavoSec's comprehensive cybersecurity solutions."
      />

      <div className="lock-float" ref={lockFloatRef}>
        <Lock3D
          ref={lockRef}
          modelPath={animationSettings.modelPath}
          primaryColor={animationSettings.primaryColor}
          secondaryColor={animationSettings.secondaryColor}
          scale={animationSettings.scale}
          autoRotate={false}
          rotationSpeed={animationSettings.rotationSpeed}
        />
      </div>

      <section className="hero-section" ref={heroRef} data-testid="hero-section">
        <div className="hero-col hero-left hero-animate">
          <span className="hero-tagline">AUTONOMOUS CYBERSECURITY PLATFORM</span>
          <h1 className="hero-heading-left">
            Break Before<br /><span className="hero-accent-green">Hackers</span> Do
          </h1>
          <p className="hero-desc-left">
            HavoSec autonomously simulates attacks, detects vulnerabilities, and
            protects your systems in real time
          </p>
        </div>

        <div className="hero-col hero-center-col">
          <div className="hero-bg-visuals">
            <div className="bg-ring ring-1"></div>
            <div className="bg-ring ring-2"></div>
            <div className="bg-ring ring-3"></div>
            <div className="bg-glow"></div>
          </div>
        </div>

        <div className="hero-col hero-right hero-animate">
          <span className="hero-tagline">PROACTIVE. AUTONOMOUS. RELENTLESS</span>
          <h2 className="hero-heading-right">
            Security That<br />Thinks Like an<br />
            <span className="hero-accent-purple">Attacker</span>
          </h2>
          <p className="hero-desc-right">
            Offensive AI meets defensive intelligence to give you continuous
            protection without constant human intervention
          </p>
        </div>

        <div className="hero-scroll-hint">
          <button onClick={scrollDown} className="scroll-hint">
            SCROLL TO EXPLORE
            <span className="scroll-line"></span>
          </button>
        </div>
      </section>

      <div className="marquee-wrap" ref={marqueeWrapRef}>
        <MarqueeStrip />
      </div>

      <div className="achieve-story" ref={achieveStoryRef}>
        <div className="achieve-sticky">
          <div className="achieve-headline-wrap" ref={headlineRef}>
            <div className="story-heading achieve-heading">
              <span className="story-kicker">Proof, not promises</span>
              <span className="achieve-headline">Trusted by<br />Industry Leaders</span>
              <p>Security teams use HavoSec to turn continuous risk into decisive action.</p>
            </div>
          </div>
          {storyAchievements.map((a, i) => (
            <div
              key={a.id}
              className="achieve-panel"
              ref={el => {
                if (el) panelRefs.current[i] = el
              }}
            >
              <article className={`stat-wrap ${i % 2 === 0 ? 'stat-left' : 'stat-right'}`}>
                <span className="stat-index">0{i + 1}</span>
                <div className="stat-icon-wrap"><a.icon className="stat-svg" /></div>
                <div className="stat-num">{a.display}</div>
                <div className="stat-label">{a.label}</div>
                <p className="stat-desc">{a.desc}</p>
                <span className="stat-line" />
              </article>
            </div>
          ))}
        </div>
      </div>

      <div
        className="feat-story"
        ref={featuresSectionRef}
        data-testid="features-section"
        style={{ height: `calc((${displayFeatures.length} + 1) * 100vh)` }}
      >
        <div className="feat-sticky">
          <div className="feat-headline-wrap" ref={featHeadlineRef}>
            <div className="story-heading feature-heading">
              <span className="story-kicker">Always one move ahead</span>
              <span className="feat-headline">Advanced<br />Security Features</span>
              <p>A unified security layer that sees, decides and acts at machine speed.</p>
            </div>
          </div>

          <div className="feat-content" ref={featContentRef}>
            <div className="feat-left">
              <span className="feat-eyebrow">Security command centre</span>
              <ul className="feat-list">
                {displayFeatures.map((feature, i) => (
                  <li
                    key={i}
                    className={`feat-list-item ${featActiveIdx === i ? 'is-active' : ''}`}
                  >
                    {feature.title}
                  </li>
                ))}
              </ul>
              <div className="feat-counter">
                <span>{featActiveIdx + 1}</span>
                <span className="feat-counter-sep">&nbsp;—&nbsp;</span>
                <span>{displayFeatures.length}</span>
              </div>
            </div>

            <div className="feat-right">
              {displayFeatures.map((feature, i) => (
                <div
                  key={i}
                  className={`feat-detail ${featActiveIdx === i ? 'is-active' : ''}`}
                >
                  <div className="feat-card-no">0{i + 1}</div>
                  <div className="feat-detail-icon">
                    {getFeatureIcon(i)}
                  </div>
                  <h3 className="feat-detail-title">{feature.title}</h3>
                  <p className="feat-detail-desc">{feature.description}</p>
                  {feature.benefit && (
                    <div className="feat-detail-benefit">
                      {feature.benefit}
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>

      <section className="demo-section" data-testid="demo-section">
        <div className="container">
          <div className="demo-card">
            <div className="demo-content">
              <div className="demo-text">
                <div className="demo-title-group">
                  <h2 className="demo-title">{demoTitle}</h2>
                  <h2 className="demo-title2">{demoTitle2}</h2>
                </div>
                <p className="demo-description">{demoDescription}</p>
                <LuxuryButton
                  variant="sweep"
                  onClick={() => navigate(demoButtonLink)}
                  size="xl"
                  className="demo-cta-button"
                  data-testid="demo-cta-button"
                >
                  {demoButtonText}
                </LuxuryButton>
              </div>
              <div className="demo-image">
                <img
                  src="https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=600&h=400&fit=crop"
                  alt="Security Operations Center"
                />
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  )
}

export default Home

// frontend/src/views/Home.vue
<template>
  <div class="home-page">
    <!-- Hero Section with 3D Animation -->
    <section class="hero-section" data-testid="hero-section">
      <div class="hero-content">
        <div class="hero-text">
          <h1 class="hero-title" data-testid="hero-title">
            {{ heroTitle }}
            <span class="text-gradient">HavoSec</span>
          </h1>
          <p class="hero-description" data-testid="hero-description">
            {{ heroSubtitle }}
          </p>
        </div>
        
        <!-- 3D Lock Model -->
        <div class="hero-animation" data-testid="3d-animation">
          <Lock3D />
        </div>
      </div>
    </section>

    <!-- Achievements Section -->
    <section class="achievements-section glass" data-testid="achievements-section">
      <div class="container">
        <h2 class="section-title">Trusted by Industry Leaders</h2>
        <div class="achievements-grid">
          <div 
            v-for="achievement in achievements" 
            :key="achievement.id"
            class="achievement-card"
            :data-testid="`achievement-${achievement.id}`"
          >
            <div class="achievement-number">{{ achievement.number }}</div>
            <div class="achievement-label">{{ achievement.label }}</div>
          </div>
        </div>
      </div>
    </section>

    <!-- Features and Benefits -->
    <section class="features-section" ref="featuresSection" data-testid="features-section">
      <div class="container">
        <h2 class="section-title">{{ featuresTitle }}</h2>
        <div class="features-grid">
          <div 
            v-for="(feature, index) in displayFeatures" 
            :key="index"
            class="feature-card glass"
            :data-testid="`feature-${index}`"
          >
            <div class="feature-icon">
              <component :is="getFeatureIcon(index)" class="w-8 h-8" />
            </div>
            <h3 class="feature-title">{{ feature.title }}</h3>
            <p class="feature-description">{{ feature.description }}</p>
            <div v-if="feature.benefit" class="feature-benefit">
              <strong>Benefit:</strong> {{ feature.benefit }}
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- 3D Examples Gallery -->
    <!-- <section class="examples-section-3d" data-testid="examples-section">
      <div class="container">
        <h2 class="section-title">See HavoSec in Action</h2>
        <p class="section-subtitle">
          Explore our advanced cybersecurity solutions through interactive demonstrations
        </p>
        <ExamplesGallery3D />
      </div>
    </section> -->

    <!-- Schedule Demo Component -->
    <section class="demo-section glass" data-testid="demo-section">
      <div class="container">
        <div class="demo-content">
          <div class="demo-text">
            <h2 class="demo-title">Ready to Protect Your</h2>
            <h2 class="demo-title2">Organization?</h2>
            <p class="demo-description">
              Get a personalized demonstration of HavoSec 
              and see how we can strengthen your cybersecurity posture.
            </p>
            <LuxuryButton 
              @click="$router.push('/book-demo')"
              size="xl"
              data-testid="demo-cta-button"
            >
              Schedule Your Demo Today
            </LuxuryButton>
          </div>
          <div class="demo-image">
            <img 
              src="https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=600&h=400&fit=crop&crop=center" 
              alt="Security Operations Center"
            />
          </div>
        </div>
      </div>
    </section>
  </div>
</template>

<script setup>
import { ref, computed, onMounted, onUnmounted } from 'vue'
import { gsap } from 'gsap'
import { ScrollTrigger } from 'gsap/ScrollTrigger'
import LuxuryButton from '@/components/LuxuryButton.vue'
import ExamplesGallery3D from '@/components/ExamplesGallery3D.vue'
import Lock3D from '@/components/Lock3D.vue'
import { useContentStore } from '@/stores/content'
import { 
  ShieldCheckIcon, 
  EyeIcon, 
  BoltIcon, 
  ChartBarIcon,
  ExclamationTriangleIcon,
  ClockIcon
} from '@heroicons/vue/24/outline'

gsap.registerPlugin(ScrollTrigger)

const contentStore = useContentStore()
const featuresSection = ref(null)

// Icon mapping for features
const featureIcons = [ShieldCheckIcon, EyeIcon, BoltIcon, ChartBarIcon, ExclamationTriangleIcon, ClockIcon]

function getFeatureIcon(index) {
  return featureIcons[index % featureIcons.length]
}

// Dynamic content with fallbacks
const heroTitle = computed(() => {
  const title = contentStore.hero?.title || 'Secure Your Digital Assets with'
  // Remove "HavoSec" from API title if present to avoid duplication
  return title.replace(/\s*(HavoSec|with HavoSec)\s*$/i, '').trim() + ' '
})

const heroSubtitle = computed(() => 
  contentStore.hero?.subtitle || 'Advanced cybersecurity analytics and threat detection platform designed for modern organizations. Real-time monitoring, AI-powered insights, and automated defense mechanisms.'
)

const featuresTitle = computed(() => 
  contentStore.features?.title || 'Advanced Security Features'
)

const displayFeatures = computed(() => {
  if (contentStore.features?.items?.length) {
    return contentStore.features.items
  }
  // Fallback features
  return defaultFeatures
})

const achievements = [
  { id: 1, number: '50M+', label: 'Threats Blocked Daily' },
  { id: 2, number: '99.9%', label: 'Uptime Guarantee' },  
  { id: 3, number: '500+', label: 'Enterprise Clients' },
  { id: 4, number: '24/7', label: 'Security Monitoring' }
]

const defaultFeatures = [
  {
    title: 'Real-Time Threat Detection',
    description: 'AI-powered threat detection that identifies and blocks attacks in milliseconds.',
    benefit: 'Reduce security incidents by 95% with proactive threat prevention.'
  },
  {
    title: 'Advanced Monitoring',
    description: 'Comprehensive visibility across your entire digital infrastructure.',
    benefit: 'Complete security oversight with zero blind spots in your network.'
  },
  {
    title: 'Automated Response',
    description: 'Instant automated responses to security threats and incidents.',
    benefit: 'Minimize damage with response times under 10 seconds.'
  },
  {
    title: 'Analytics Dashboard',
    description: 'Rich analytics and reporting for security insights and compliance.',
    benefit: 'Make data-driven security decisions with comprehensive insights.'
  },
  {
    title: 'Incident Management',
    description: 'Streamlined incident response and investigation workflows.',
    benefit: 'Reduce incident resolution time by 80% with automated workflows.'
  },
  {
    title: '24/7 Monitoring',
    description: 'Round-the-clock security monitoring and threat hunting.',
    benefit: 'Never miss a threat with continuous security surveillance.'
  }
]

// Examples data removed - now using ExamplesGallery3D component

function scrollToFeatures() {
  featuresSection.value?.scrollIntoView({ behavior: 'smooth' })
}

function initScrollAnimations() {
  // Hero section animation
  gsap.fromTo('.hero-title', 
    { y: 100, opacity: 0 },
    { y: 0, opacity: 1, duration: 1, ease: 'power3.out' }
  )

  gsap.fromTo('.hero-description', 
    { y: 50, opacity: 0 },
    { y: 0, opacity: 1, duration: 1, delay: 0.3, ease: 'power3.out' }
  )

  gsap.fromTo('.hero-actions', 
    { y: 30, opacity: 0 },
    { y: 0, opacity: 1, duration: 1, delay: 0.6, ease: 'power3.out' }
  )

  // Achievements animation
  gsap.fromTo('.achievement-card',
    { y: 50, opacity: 0 },
    {
      y: 0,
      opacity: 1,
      duration: 0.8,
      stagger: 0.2,
      scrollTrigger: {
        trigger: '.achievements-section',
        start: 'top 80%'
      }
    }
  )

  // Features animation
  gsap.fromTo('.feature-card',
    { y: 50, opacity: 0, scale: 0.9 },
    {
      y: 0,
      opacity: 1,
      scale: 1,
      duration: 0.8,
      stagger: 0.15,
      scrollTrigger: {
        trigger: '.features-section',
        start: 'top 80%'
      }
    }
  )

  // 3D Examples Gallery animation
  gsap.fromTo('.examples-section-3d',
    { y: 50, opacity: 0 },
    {
      y: 0,
      opacity: 1,
      duration: 0.8,
      scrollTrigger: {
        trigger: '.examples-section-3d',
        start: 'top 80%'
      }
    }
  )
}

onMounted(() => {
  initScrollAnimations()
})

onUnmounted(() => {
  ScrollTrigger.killAll()
})
</script>

<style scoped>
.home-page {
  min-height: 100vh;
}

/* Hero Section */
.hero-section {
  min-height: calc(100vh - 80px);
  @apply relative flex items-center justify-center;
  background: var(--bg-secondary, #f8f9fa);
  overflow: hidden;
  transition: background-color 0.3s ease;
}

.dark .hero-section {
  background: var(--bg-primary, #000000);
}

.hero-content {
  @apply container mx-auto px-6 grid grid-cols-1 lg:grid-cols-2 gap-12 items-center;
  max-width: 1200px;
}

.hero-text {
  @apply space-y-6;
}

.hero-title {
  @apply text-4xl md:text-6xl font-bold leading-tight;
  color: #1a202c;
}

.dark .hero-title {
  color: #f7fafc;
}

.hero-description {
  @apply text-xl text-gray-600 leading-relaxed;
}

.dark .hero-description {
  @apply text-gray-300;
}

.hero-actions {
  @apply flex flex-col sm:flex-row gap-4;
}

.hero-animation {
  @apply flex justify-center items-center;
  min-height: 520px;
  width: 100%;
}

/* Achievements Section */
.achievements-section {
  @apply py-20 my-20;
}

.achievements-grid {
  @apply grid grid-cols-2 md:grid-cols-4 gap-6 mt-12;
}

.achievement-card {
  @apply text-center p-6 rounded-xl;
  background: rgba(255, 255, 255, 0.1);
  backdrop-filter: blur(10px);
  border: 1px solid rgba(255, 255, 255, 0.2);
}

.dark .achievement-card {
  background: rgba(0, 0, 0, 0.3);
  border: 1px solid rgba(126, 99, 119, 0.2);
}

.achievement-number {
  @apply text-3xl md:text-4xl font-bold mb-2;
  color: #00b090;
}

.achievement-label {
  @apply text-gray-600 font-medium;
}

.dark .achievement-label {
  @apply text-gray-300;
}

/* Features Section */
.features-section {
  @apply py-20;
}

.features-grid {
  @apply grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 mt-12;
}

.feature-card {
  @apply p-8 rounded-xl transition-all duration-300 hover:scale-105;
}

.feature-icon {
  @apply mb-6 p-3 rounded-lg w-fit;
  background: #00b090;
  color: white;
}

.feature-title {
  @apply text-xl font-bold mb-4;
  color: #1a202c;
}

.dark .feature-title {
  color: #f7fafc;
}

.feature-description {
  @apply text-gray-600 mb-4 leading-relaxed;
}

.dark .feature-description {
  @apply text-gray-300;
}

.feature-benefit {
  @apply text-sm p-3 rounded-lg;
  background: rgba(126, 99, 119, 0.1);
  color: #ffffff;
}

.dark .feature-benefit {
  background: rgba(103, 62, 230, 0.2);
  color: #ffffff;
}

/* 3D Examples Gallery Section */
.examples-section-3d {
  @apply py-20;
}

.section-subtitle {
  @apply text-lg text-gray-600 text-center mb-12 max-w-3xl mx-auto;
}

.dark .section-subtitle {
  @apply text-gray-300;
}

/* Old example styles removed - now using ExamplesGallery3D component */

/* Demo Section */
.demo-section {
  @apply py-20 my-20;
}

.demo-content {
  @apply grid grid-cols-1 lg:grid-cols-2 gap-12 items-center;
}

.demo-title {
  @apply text-3xl md:text-4xl font-bold mb-6;
  color: #1a202c;
}

.dark .demo-title {
  color: #f7fafc;
}

.demo-title2 {
  @apply text-3xl md:text-4xl font-bold mb-6;
  color: #1a202c;
}

.dark .demo-title2 {
  color: #00b090;
}

.demo-description {
  @apply text-lg text-gray-600 mb-8 leading-relaxed;
}

.dark .demo-description {
  @apply text-gray-300;
}

.demo-image {
  @apply rounded-xl overflow-hidden;
}

.demo-image img {
  @apply w-full h-auto object-cover;
}

/* Common Styles */
.container {
  @apply max-w-7xl mx-auto px-6;
}

.section-title {
  @apply text-3xl md:text-4xl font-bold text-center mb-4;
  color: #1a202c;
}

.dark .section-title {
  color: #f7fafc;
}

/* Responsive Design */
@media (max-width: 768px) {
  .hero-content {
    @apply grid-cols-1 text-center;
  }
  
  .hero-animation {
    @apply order-first;
    min-height: 360px;
  }
  
  .achievements-grid {
    @apply grid-cols-2;
  }
  
  .features-grid {
    @apply grid-cols-1;
  }
}
</style>
